# fly.toml app configuration file generated for art-post on 2023-09-08T19:07:01-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "art-post"
primary_region = "lax"

[build]

[env]
SEND_GRID = "secrets.SEND_GRID"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
