# fly.toml app configuration file generated for divine-haze-7243 on 2023-09-27T12:18:19-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "art-post"
primary_region = "lax"

[build]


[mounts]
  source="artpost_dat"
  destination="/data"

[env]
SEND_GRID= "secrets.SEND_GRID"


[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
